### ISSUE TITLE
sample request

### ISSUE THREAD

**Issue by Tobbyte** [diegoveloper/flutter-samples#10]
Hey Diego,

found an old tweet of yours https://twitter.com/diegoveloper/status/1054400640795992064
and wanted to ask you kindly if you could post the code for linking the two bottom scroll views?
I'm working on something similar and can't get it to work smoothly.
I found your sample for scroll_sync, but f.e. I have no idea how to clamp a list to it's max extend when the other is longer...

**Comment by diegoveloper** [comment]
Sorry the code is not available, but you can do easily with two ListViews with horizontal axis
