### ISSUE TITLE
Unresolved reference: getFlutterView and Type mismatch: inferred type is MainActivity but FlutterEngine was expected

### ISSUE THREAD

**Issue by sumitrvi** [diegoveloper/flutter-samples#13]
Type mismatch: inferred type is MainActivity but FlutterEngine was expected
flutter_app/android/app/src/main/kotlin/com/example/flutter_app/MainActivity.kt: (23, 19): Unresolved reference: getFlutterView
flutter_app/android/app/src/main/kotlin/com/example/flutter_app/MainActivity.kt: (26, 17): Unresolved reference: getFlutterView

Mainactivity
 override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        //make transparent status bar
        window.statusBarColor = 0x00000000
        GeneratedPluginRegistrant.registerWith(this)
        //Remove full screen flag after load
        val vto = getFlutterView().getViewTreeObserver()
        vto.addOnGlobalLayoutListener(object : ViewTreeObserver.OnGlobalLayoutListener {
            override fun onGlobalLayout() {
                getFlutterView().getViewTreeObserver().removeOnGlobalLayoutListener(this)
                window.clearFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN)
            }
        })
    }

**Comment by diegoveloper** [comment]
Is this an error? Warning? Add flutter doctor log here. 
What you see on the screen?
Can you compile?
Does it crash in runtime?

**Comment by UsabilitySpace** [comment]
I am experiencing just the same problem. 

Using **Flutter new v2 embedding**, I'm trying to built a transparent app according to recommendations provided here: 

- (1) [https://github.com/NMateu/flutter_transparent_app/ ](https://github.com/NMateu/flutter_transparent_app/ )
- (2) [https://github.com/flutter/flutter/issues/28844#issuecomment-478939888 ](https://github.com/flutter/flutter/issues/28844#issuecomment-478939888 )

As far as (1) and (2) represent Flutter embedding v1, while I need Flutter embedding v2, I'm trying to convert java code provided by (1) and stored in the next java file: 

-  /android/app/src/main/java/com/example/transparent_app/MainActivity.java 

... to kt code that according to Flutter embedding v2 rules should be stored in the next kt file: 

- /android/app/src/main/[package_name]/MainActivity.kt . 

I'm using **Android Studio**, and **the Studio** readily helps me convert java code to kt code syntactically. But, as it is thought expected, **Android Studio** is unable to convert semantics of the code, so I receive error which is just the same with yours: 

`Type mismatch: inferred type is MainActivity but FlutterEngine was expected`.
