### ISSUE TITLE
Initial index / infinite loop and Next/Per button

### ISSUE THREAD

**Issue by shayanmomeni** [diegoveloper/flutter-samples#16]
Hello , Hope you doing great , Thanks for your great work . I will be appreciate if you can help me .
I used same package " circle_wheel_scroll " , and same example code in read me , to generate a list .
and also if possible i wanna add Next and Previous button like a carousel . Thanks in advance

**Comment by diegoveloper** [comment]
Sorry this isn't an issue. This question should be moved to stackoverflow.

**Comment by shayanmomeni** [comment]
Thanks Diego , if you can help me to get initial index with this package I will be appreciate . I generate 10000 item to get feel like infinite loop , but I want to start with a specific index , like from middle not start item . 


Thanks in advance
