### ISSUE TITLE
Show the drawer menu icon

### ISSUE THREAD

**Issue by alfianakbar** [diegoveloper/flutter-samples#19]
Firstly, thank you for sharing!
I want to know how to show the drawer menu icon (burger icon) on the left side of appbar.
File: flutter-samples/lib/appbar_sliverappbar/main_appbar_sliverappbar.dart
Thanks in advance!

**Comment by diegoveloper** [comment]
Is this question related to any sample I made?

**Comment by alfianakbar** [comment]
Yes, I have edited the question

**Comment by alfianakbar** [comment]
Your medium article:
https://medium.com/flutter-community/flutter-increase-the-power-of-your-appbar-sliverappbar-c4f67c4e076f

**Comment by diegoveloper** [comment]
Just check the sample1 inside that folder.

**Comment by alfianakbar** [comment]
Thank you for the quick reply.

I actually work on the sample2.dart part. When I implemented sample2.dart with Drawer, the menu icon was missing. I try to add appbar in the Scaffold, but it's just bad.
<img width="362" alt="Screen Shot 2020-05-11 at 9 19 15" src="https://user-images.githubusercontent.com/989885/81518589-b6254880-9368-11ea-8b19-69aa3b630b7f.png">

Is there any chance to reveal the menu icon in sliverappbar?

Thanks in advance.

**Comment by diegoveloper** [comment]
@alfianakbar I updated the sample2.dart, check again.

**Comment by alfianakbar** [comment]
Thank you @diegoveloper ! It works perfectly!

**Comment by diegoveloper** [comment]
sure :),  don't forget to share my repo with your friends   , this is my
twitter: https://twitter.com/diegoveloper


*    Diego Velásquez*
*www.diegoveloper.com <http://www.diegoveloper.com>*
