### ISSUE TITLE
How to use future builder inside silverlist;

### ISSUE THREAD

**Issue by atta1234** [diegoveloper/flutter-samples#21]
SliverList(
                    delegate: SliverChildBuilderDelegate((_, index) {
                      final song = songs[index % songs.length];
                      return ListTile(
                        leading: Image.network(
                          song.image,
                          height: 30,
                          fit: BoxFit.cover,
                        ),
                        title: Text(
                          song.title,
                        ),
                        trailing: IconButton(
                          onPressed: () => null,
                          icon: Icon(
                            Icons.add,
                            color: Colors.pinkAccent,
                          ),
                        ),
                      );
                    }, childCount: 20),
                  ),

inside this one,got it from your file

**Comment by diegoveloper** [comment]
This should be in stackoverflow

**Comment by atta1234** [comment]
> This should be in stackoverflow

Dear you have done it, i m using your exapmles, but you have used static list and i m getting data from api, so i need to use future builder inside that sliverlist,if you can help please

**Comment by GowthamF** [comment]
I could help you. Drop me a mail to this gowthamseafret@gmail.com

**Comment by atta1234** [comment]
> gowthamseafret@gmail.com

i have sent you an email, please have a look !
