### ISSUE TITLE
I can not run on my iOS device

### ISSUE THREAD

**Issue by cheshuangchun** [diegoveloper/flutter-samples#27]
### When I use  " flutter run" ,I got the error as follows:

Launching lib/main.dart on Ace in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: YPGH95V8AL
Running pod install...                                           1,372ms
Running Xcode build...                                                  
Xcode build done.                                            4.4s
Failed to build iOS app
Error output from Xcode build:
↳
    2021-07-29 17:37:37.812 xcodebuild[17585:369397] [MT] PluginLoading: Required plug-in compatibility UUID F56A1938-53DE-493D-9D64-87EE6C415E4D for plug-in at path '~/Library/Application
    Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
    2021-07-29 17:37:38.502 xcodebuild[17585:369500]  DVTAssertions: Warning in
    /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-18108/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 94de9a9a80dc218095a7f7b77686a7ad392521c1 was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fc8647ec510>
    Method:   -platform
    Thread:   <NSThread: 0x7fc860a0eb10>{number = 7, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-07-29 17:37:38.641 xcodebuild[17585:369503]  DVTAssertions: Warning in
    /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-18108/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 94de9a9a80dc218095a7f7b77686a7ad392521c1 was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fc8647ec510>
    Method:   -platform
    Thread:   <NSThread: 0x7fc860f183b0>{number = 9, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    2021-07-29 17:37:38.716 xcodebuild[17585:369503]  DVTAssertions: Warning in
    /Library/Caches/com.apple.xbs/Sources/DVTiOSFrameworks/DVTiOSFrameworks-18108/DTDeviceKitBase/DTDKRemoteDeviceData.m:371
    Details:  (null) deviceType from 94de9a9a80dc218095a7f7b77686a7ad392521c1 was NULL when -platform called.
    Object:   <DTDKMobileDeviceToken: 0x7fc8647ec510>
    Method:   -platform
    Thread:   <NSThread: 0x7fc860f183b0>{number = 9, name = (null)}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **

Xcode's output:
↳
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    /Users/cheshuangchun/Downloads/flutter-samples-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported
    deployment target versions is 9.0 to 14.5.99. (in target 'Flutter' from project 'Pods')
    /Users/cheshuangchun/Downloads/flutter-samples-master/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported
    deployment target versions is 9.0 to 14.5.99. (in target 'FMDB' from project 'Pods')
    error: No profiles for 'com.teamgo.sample.flutter-samples' were found: Xcode couldn't find any iOS App Development provisioning profiles matching 'com.teamgo.sample.flutter-samples'.
    Automatic signing is disabled and unable to generate a profile. To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Runner' from project 'Runner')

Could not build the precompiled application for the device.

Error launching application on Ace.

please help me,thank you very much!

**Comment by diegoveloper** [comment]
It's related to your own certificate - development profile
