### ISSUE TITLE
Content overlays on TabBar in CollapsingToolbar

### ISSUE THREAD

**Issue by niegus** [diegoveloper/flutter-samples#3]
I've used your CollapsingToolbar as a example for my app but when a scroll is done, the content of the body overlays the TabBar.

Any idea on this?

**Comment by diegoveloper** [comment]
Could you add a minimum sample code to reproduce the issue?

**Comment by niegus** [comment]
Yes, basically your "main_collapsing_toolbar.dart" but remove the Center from the body:

body: Text("Sample text"),

**Comment by diegoveloper** [comment]
Hmm, inside the build  method for _SliverAppBarDelegate set a color for
your Container and let me know if it works for you.

**Comment by niegus** [comment]
I've tried that, but the behaviour is the same.

@override
  Widget build(
      BuildContext context, double shrinkOffset, bool overlapsContent) {
    return new Container(
      child: _tabBar,
      color: Colors.amber.shade400,
    );
  }

**Comment by diegoveloper** [comment]
Could you add a screenshot please?

**Comment by niegus** [comment]
This is the behaviour.
https://im2.ezgif.com/tmp/ezgif-2-3f2a70520a8a.gif

When I set the color.
https://im2.ezgif.com/tmp/ezgif-2-8ccdb1310313.gif

**Comment by diegoveloper** [comment]
ok, it looks like there is an issue and a solution also, check this : https://github.com/zmtzawqlp/Flutter_Candies/tree/master/extended_nested_scroll_view
