### ISSUE TITLE
Screenshots in README.md

### ISSUE THREAD

**Issue by twisstosin** [diegoveloper/flutter-samples#4]
Hi, I think It'll be really helpful for people looking for specific implementations in flutter if you could add screenshots as well.

Thanks

**Comment by diegoveloper** [comment]
yeah, also would be great if someone can do it for me and send a Pull Request :) I'll be happy to merge that

**Comment by twisstosin** [comment]
Cool, I'll send

**Comment by diegoveloper** [comment]
Would be great if you can add these :
 - Add **App Clone - Twitter Profile**
 - Add **Animations - List - Details (Dragon Ball)**

Thanks!

**Comment by twisstosin** [comment]
Cool, I can't find the links to them though.

Have you created them or you're saying I could contribute those?

**Comment by diegoveloper** [comment]
Oh , well, there are no links, but you can run the app and generate a gif
if you can :)
