### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by shriharip** [diegoveloper/flutter-samples#6]
Could you please let me know what kind of licensing you are planning to set this up with?

Very nice work!! thanks.

**Comment by diegoveloper** [comment]
What do you mean by licensing?

**Comment by shriharip** [comment]
like is it BSD, MIT etc. At least for the apps clone script, you have quite a few code which I want to use and wanted to know what kind of licensing you plan to do with the project.

**Comment by diegoveloper** [comment]
thanks added now!
