### ISSUE TITLE
Persistent tab is not really persistent

### ISSUE THREAD

**Issue by shaxxx** [diegoveloper/flutter-samples#8]
Persistent tab is not really persisting it's view in some situations which leads to app crash when initState is called trying to init state on disposed object.
> FlutterError (setState() called after dispose(): _Page2State#faac0(lifecycle state: defunct, not mounted)

To reproduce try to add two more tab pages and jump around randomly from tab to tab (it takes several tab changes to reproduce).

Here's the repro code
```
class MainPersistentTabBar extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 4,
      child: Scaffold(
        appBar: AppBar(
          bottom: TabBar(
            tabs: [
              Tab(
                icon: Icon(Icons.directions_car),
                text: "Non persistent",
              ),
              Tab(icon: Icon(Icons.directions_transit), text: "Persistent"),
              Tab(icon: Icon(Icons.directions_bike), text: "Non Persistent"),
              Tab(icon: Icon(Icons.directions_boat), text: "Non Persistent"),
            ],
          ),
          title: Text('Persistent Tab Demo'),
        ),
        body: TabBarView(
          children: [
            Page1(),
            Page2(),
            Text('Page 3'),
            Text('Page 4'),
          ],
        ),
      ),
    );
  }
}
```

**Comment by diegoveloper** [comment]
I updated the code with some changes, try again and let me know if it works for you. Thanks

**Comment by shaxxx** [comment]
It's not crashing, but it's not persistent either.  Notice the scroll position state and first item in the list
![repro](https://user-images.githubusercontent.com/1778875/59740956-dee0b300-9269-11e9-8b17-2e009baf7a54.gif)

**Comment by diegoveloper** [comment]
hmm I don't understand, the first element is 'not persistent' of course, only the tab 'persistent' is persistent,  the scroll index remains the same when you change between tabs.

**Comment by shaxxx** [comment]
Maybe the fact the gif is in loop is misleading. 
Video starts on non persistent tab with text "sun aut facere"
Then jump to persistent tab which is by default set to "accuamus beateae..." and no scroll offset.
Then I scrolled to "nihil et amet". 
Then started switching tabs
- Test 1 -> Test 2 -> Persistent tab (all looks  good)
Then
- Non persistent -> Persistent (all looks good)
Then 
- Test 1 -> Test 2 -> Test 1 -> Non persistent -> Persistent (state is lost)
Scroll position is lost and text is back to "accuamus beateae..."

**Comment by diegoveloper** [comment]
what version of flutter are you using?  could you run flutter doctor?  are you testing on android or ios ? 

This is mine: 

```
[✓] Flutter (Channel dev, v1.7.4, on Mac OS X 10.14.5 18F132, locale en-PE)
```
I'm testing on iOS simulator and this is the result : 

![gif_no_issue](https://user-images.githubusercontent.com/4898256/59742894-51cf3700-9234-11e9-9f10-ab980cf9b448.gif)

**Comment by shaxxx** [comment]
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.829], locale hr-HR)
>
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Android Studio (version 3.4)
> [√] VS Code, 64-bit edition (version 1.35.0)
> [√] Connected device (1 available)

Testing on Android Pie, both emulator and device.

**Comment by diegoveloper** [comment]
hmm so it could be something related with android, could you try in an iOS device/simulator please?

**Comment by myriky** [comment]
same on you!
I've had the same problem as you.
I was using the v1.5.4-hotfix.2 stable version, but I upgraded it to v1.7.10-beta the problem was solved.
