### ISSUE TITLE
I use your circular_list and i have a question

### ISSUE THREAD

**Issue by Yuiie** [diegoveloper/flutter-samples#9]
Hi,
I use your circular_list and i would like to open a new route when i click on images,
i tried many things but didn't work, i would really appreciate it if u can lend me a hand.

ps: sorry my english is sooo poor x'(

**Comment by diegoveloper** [comment]
there is an open issue about that inside the lib package https://github.com/DenisBogatirov/circle_wheel_scroll/issues/2

**Comment by Yuiie** [comment]
it's me again, sorry but i don't understand the post u linked i read it and do somes tests but that didn't work. Can u make me an sample please i use your basic circular_list/circular_list_page.dart i just want to click on every images to open a new pages.

**Comment by diegoveloper** [comment]
I'm using this package https://pub.dev/packages/circle_wheel_scroll  and it
looks like doesn't have implemented onTap .


*Diego Velásquez López*

**Comment by Yuiie** [comment]
oki thanks thats sad it was a nice widget
